#!/usr/bin/env bash

# Wrapper to run emercoin-cli inside the Docker container
# Usage examples:
#   ./emercoin-cli getblockchaininfo
#   ./emercoin-cli getbestblockhash
#   ./emercoin-cli name_show ness:dns-reverse-proxy-config

# On Windows Git Bash, MSYS_NO_PATHCONV avoids accidental path mangling
MSYS_NO_PATHCONV=1 docker exec -it emercoin-core emercoin-cli -datadir=/data "$@"
