#!/usr/bin/env bash

# Wrapper to run yggdrasilctl inside the Yggdrasil Docker container
# Usage examples:
#   ./yggdrasil-cli getPeers
#   ./yggdrasil-cli getSelf
# All arguments are passed through to the in-container yggdrasilctl.

# On Windows Git Bash, MSYS_NO_PATHCONV avoids accidental path mangling
MSYS_NO_PATHCONV=1 docker exec -it yggdrasil yggdrasilctl "$@"
